name: Deploy to Firebase Hosting on main
on:
  push:
    branches:
      - main
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: build
        run: npm run build
      - name: Run Jest
        uses: stefanoeb/jest-action@1.0.3
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_STREET_FOR_YOU_741C8 }}'
          projectId: street-for-you-741c8
          channelId: live
